### ISSUE TITLE
manifest.webapp paths start out "wrong"

### ISSUE THREAD

**Issue by willkg** [mozilla/mortar-tab-view#2]
I mostly ported my magic10ball app over to use the tab template (though it's not exactly using tabs, but ... details). The biggest issue I bumped into is that the manifest.webapp file expects things to live in the root path, but if you use ghdeploy, they live in a subdirectory. It took me a while to figure out what was going on.

Seems like if the default and suggested workflow is to use ghdeploy, then it'd help to either:
1. have a TODO file that lists the things the developer needs to change in the template and where they are which would include the paths in the manifest.webapp file, and/or
2. have "volo create myapp..." expand some strings in the manifest.webapp so they were correct for the ghdeploy case

I think the TODO one is probably the easiest and it'd catch someone's eye as soon as they generated an app from the template. It'd allow you to notify developers of other things they need to change. You could probably automatically generate it by grepping the codebase for TODO: comments or something like that, too.

Maybe there are other options?

**Comment by jlongster** [comment]
We specify this step in our tutorials, but you're right that we at least need a notice somewhere. What do you think about adding a notice to the ghdeploy command, something along the lines of "did you set the right launch path?"
