### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by willkg** [mozilla/mortar-tab-view#3]
The template should have a LICENSE file with text along the lines of "You need to choose a license. Go xxx to get help." or something like that.

**Comment by willkg** [comment]
Also, the template doesn't specify the license the code it's distributing is under. Ergo it's not distributed under any license and thus under regular copyright.

There should at least be LICENSE information in the README, but preferably a separate LICENSE file denoting the license of the mortar-specific code as well as copyright and license of all other code being distributed.

Pretty sure this is a problem with all the mortar templates, too.

If you tell me the license this is being distributed under, I can probably figure out the rest and provide a patch with a LICENSE file.

**Comment by jlongster** [comment]
That's a very good point. There used to be a license but since we refactored the templates I think it got lost. I'll figure out what license we need and put it in.

**Comment by sole** [comment]
LICENSE is present now.
