### ISSUE TITLE
workflow for deploying is confusing

### ISSUE THREAD

**Issue by willkg** [mozilla/mortar-tab-view#4]
I don't really understand the flow for deploying. Is it?:
1. `volo appcache`
2. `volo build`
3. `volo ghdeploy`

This should be documented somewhere or made obvious in some way. Maybe in the README in the Usage section?

If someone walks me through it, I can submit a patch.

**Comment by jlongster** [comment]
Our tutorials and screencasts arguable have gotten more love than our README. See https://developer.mozilla.org/en-US/docs/Apps/Tutorials/Weather_app_tutorial#Deployment

I think it feels intuitive after you've done it once or twice. We can add more info in the README though.

**Comment by willkg** [comment]
I had no idea those tutorials existed. If there are other people like me who are discovering the templates through github and not coming from the tutorials or something that mentions the tutorials, then maybe it's prudent to have links in the README files to the tutorials.

**Comment by sole** [comment]
Closed because we've changed the structure to something easier for beginners-you shouldn't have issues with deploying anymore.
