### ISSUE TITLE
Add please setup for jasmine testing

### ISSUE THREAD

**Issue by mcepl** [mozilla/mortar-tab-view#5]
I think that TDD is The Right Thing™ to promote, but when I tried to setup jasmine for testing mcepl/elasmotherium@85871fc9 I failed miserably. I don't ask for fixing my problems, but I would think that inclusion of some example setup for testing would help newbies like myself.

**Comment by jlongster** [comment]
It would be cool to include some kind of testing already. In response to lots of other feedback, we are restructuring all of these templates right now. We aren't going to invest much more in the templates as they are, so I would watch out for the incoming new version in the next few weeks.

**Comment by mcepl** [comment]
"few weeks" ... ouch, guys, please, hurry up! I need to present my app (showing how easy it is to develop for FF OS ;))

**Comment by mcepl** [comment]
The same goes for some illustration (examples?) how to use Backbone.models (including localStorage/indexedDB adaptors)... see e.g. http://thread.gmane.org/gmane.comp.mozilla.devel.webapps/689/

**Comment by jlongster** [comment]
To be honest, I'm not very familiar with Backbone.sync. However, the x-view stuff is really just a light wrapper around backbone, and you can still access the raw backbone layer.

Do you need to customize the model to get `sync` to work? If so, you need to create your custom model, and you can pass it to `list.add`:

``` js
var MyModel = Backbone.Model.extend({
  // ...
});

list.add(new MyModel(/* ... */));
```

**Comment by mcepl** [comment]
Hmm, which is exactly what I do in https://github.com/mcepl/elasmotherium/blob/master/www/js/app.js#L62 ... never mind, I will try to investigate this further, and hopefully somebody will react on the email list.

**Comment by sole** [comment]
Closed because we've changed the structure to something easier for beginners. Again @mcepl thanks for your contribution, we'll have it in mind for more complicated templates.
